### ISSUE TITLE
Empty Inventory

### ISSUE THREAD

**Issue by awoSYS** [joostkamphuisnl/feig-driver#1]
When reading the inventory (with a tag placed on top of the reader), I always receive empty replies. 

This is my code:

```javascript
const Reader = require('feig-driver')

// Instantiate a new Reader instance.
const reader = new Reader({
    vendorId: 2737,
    productId: 4,
    // debug: true
})

// Connect to the USB device.
reader.connect().then(() => {

    // Request the current inventory, returns a promise with all found tag ID's.
    reader.inventory().then(foundTags => {
        console.log('Tags:', foundTags)
    })

});

let readoutTask = setInterval(() =>
    reader.inventory().then(foundTags => {
        console.log('Tags:', foundTags)
    }), 5000);
```

Output: 

```
Tags: []
Tags: []
Tags: []
...
```

Maybe this has to do with an error response from the reader? Any ideas how to fix this?

I'm using a FEIG CPR40.30-USB, configured to operate in ISO Host mode. Using the FEIG Windows config tool, reading the inventory works fine.

**Comment by joostkamphuisnl** [comment]
I have not been able to test this on a CPR40 as I can only get my hands on a CPR74, but it should work according to the manual.
Also I haven't been able to test this library on a Windows machine, because I have made this library to use on a Raspberry Pi project.

An empty array usually means a Status.NoTransponder response during the readout of the inventory.
I'll quickly create a more informative response after running the inventory command, maybe it gives us a bit more information about the reason the response is empty.

**Comment by joostkamphuisnl** [comment]
Is there a chance you could test this version?
https://github.com/joostkamphuisnl/feig-driver/tree/1-empty-inventory

```js
reader.inventory().then(response => console.log(response))
```

It should show an object in the console, containing the status code, raw output and an array of tags (in your case empty).
Could you share the result?

**Comment by awoSYS** [comment]
Thanks so much for the quick response, will test this afternoon and let you know.

**Comment by awoSYS** [comment]
The reply looks like this:

```
Tags: {
  status: 'OK',
  raw: <Buffer 01 04 00 01 84 62 ad c2 07 5b 04>,
  tags: []
}
Tags: {
  status: 'OK',
  raw: <Buffer 01 04 00 01 84 62 ad c2 07 5b 04>,
  tags: []
}
Tags: {
  status: 'OK',
  raw: <Buffer 01 04 00 01 84 62 ad c2 07 5b 04>,
  tags: []
}
```

The raw buffer content contains the tag value I expect (the last 7 bytes), only parsing doesn't seem to work.

**Comment by joostkamphuisnl** [comment]
Thank you for the information, are you using ISO15693 tags?

**Comment by joostkamphuisnl** [comment]
And what is the actual tag identifier, the one you would expect for this particular tag?
I see you are using ISO14443A tags, I can try to write a parser for it.

**Comment by awoSYS** [comment]
Oh I see, my tags are sending different type of data. Actually I'm new to that stuff... Would be great, if you'd find the time to implement the appropriate parser!

**Comment by joostkamphuisnl** [comment]
Ofcourse, I will try something out.
Are you expecting 84 62 ad c2 07 5b 04?

**Comment by awoSYS** [comment]
Yes, or rather 00 84 62 ... (thats what the reader outputs using the Windows driver)! Thanks a lot!

**Comment by joostkamphuisnl** [comment]
The 00 pad on the left isn't something I can read from the actual buffer. I've updated the issue branch to return the ISO14443A tags. Could you let me know if this works for you?

https://github.com/joostkamphuisnl/feig-driver/tree/1-empty-inventory

**Comment by awoSYS** [comment]
Great, thanks a lot. Will be able to test tomorrow and let you know about the results.

**Comment by awoSYS** [comment]
Works fine! The output now looks like this: 

```
Tags: {
  status: 'OK',
  raw: <Buffer 01 04 00 01 84 62 ad c2 07 5b 04>,
  tags: [ <Buffer 84 62 ad c2 07 5b 04> ]
}
```

Thanks again!

Are you going to keep the verbose inventory return value?

**Comment by joostkamphuisnl** [comment]
Great to hear it works!
I think I will keep it like this indeed, it'll be better for future implementations and you get a good understanding of what is happening.
